# -*- coding: utf-8 -*-
"""
Created on Tue Jul 11 16:28:09 2023

@author: thiag
"""



"""GOES-16 products processing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tF-GMOUDRPZeFwslQd0fOeL_H1Jtu5mM

Fire product: 

OR_ABI-L2-FDCF-M3_G16_sYYYYJJJHHMMSSs_eYYYYJJJHHMMSSs_cYYYYJJJHHMMSSs.nc
"""

###############################################################################
# Define input and output folders and file
import os
from io import BytesIO
# import s3fs
import xarray as xr
# import cartopy.crs as ccrs
import numpy as np
import glob
from pyproj import Proj
import pandas as pd
from matplotlib import pyplot
from s3fs import S3FileSystem
import fsspec  # noqa: F401
from fsspec.asyn import (FSTimeoutError)
# import time


###############################################################################
# Initialize geometric variables
def get_lat_lon(file_system):
    files = file_system.ls('noaa-goes16/ABI-L2-FDCF/2021/'+str(200).zfill(3)+'/'+str(15).zfill(2)+'/') # list of 6 files for 2021 day 200, UTC time 15:00, 15:10, 15:20, ..., 15:50

    with fs.open(files[0], 'rb') as f:
      ds0 = xr.open_dataset(BytesIO(f.read()), engine='h5netcdf')


    sat_h = ds0.goes_imager_projection.perspective_point_height # Windows version
    sat_lon = ds0.goes_imager_projection.longitude_of_projection_origin # Windows version
    sat_sweep = ds0.goes_imager_projection.sweep_angle_axis # Windows version
    
    # sat_h = ds0.goes_imager_projection.perspective_point_height[0] #   version
    # sat_lon = ds0.goes_imager_projection.longitude_of_projection_origin[0] # ubuntu old version
    # sat_sweep = ds0.goes_imager_projection.sweep_angle_axis[0] # ubuntu old version
    # oproj=ccrs.Geostationary(central_longitude=sat_lon,satellite_height=sat_h,sweep_axis=sat_sweep)
    p = Proj(proj='geos', h=sat_h, lon_0=sat_lon, sweep=sat_sweep)
    X = np.array(ds0.x) * sat_h
    Y = np.array(ds0.y) * sat_h
    XX, YY = np.meshgrid(X,Y)
    rlon, rlat = p(XX, YY, inverse=True)
    
    return rlat,rlon

def get_files(s_year,e_year,s_day,e_day,s_hour,e_our):
    print('Getting file names')
    aux = []
    for y in range(s_year,e_year+1):
        for d in range(s_day,e_day):
            #The range of the variable 'd' will determine the days of the product
            for j in range(s_hour,e_our):
                FD = fs.ls('noaa-goes16/ABI-L2-FDCF/'+str(y)+'/'+str(d).zfill(3)+'/'+str(j).zfill(2)+'/') # list of 6 files for 2020 day 228, UTC time 15:00, 15:10, 15:20, ..., 15:50

                aux = np.append(aux,FD)
    return aux


def get_indexes_v2(min_lon,max_lon,min_lat,max_lat,rlat,rlon):
    centers_lon = np.linspace(minlon+0.25, maxlon-0.25,num=int(maxlon-minlon)*2)
    centers_lat = np.linspace(minlat+0.25, maxlat-0.25,num=int(maxlat-minlat)*2)
    
    print(centers_lon)
    print(centers_lat)
    
    for i in range(0,len(centers_lat)):
        # df2 = dados_feer.loc[(dados_feer['Latitude'] == centers_lat[i]) & (dados_feer['Longitude'] <= maxlon )
        #                    & (dados_feer['Longitude'] >= minlon ),'Ce_850'].to_numpy()
        # aux_list = np.append(aux_list,df2)
        if i == 0:
            aux = np.repeat(centers_lat[i],len(centers_lon))
            lat_lon_feer = np.column_stack((aux,centers_lon))
            # latlon = np.vstack((latlon,au2))
        else:
            # print(i)
            aux = np.repeat(centers_lat[i],len(centers_lon))
            aux2 = np.column_stack((aux,centers_lon))
            lat_lon_feer = np.vstack((lat_lon_feer,aux2))
    print(lat_lon_feer)
    matrix = lat_lon_feer
    # lat_lon_feer = np.column_stack((lat_lon_feer,aux_list))   
    
    I = np.where((rlat>=min_lat)&(rlat<=max_lat)&(rlon>=min_lon)&(rlon<=max_lon))
    index_list = []
    index_list.insert(0,I)
    print(index_list)
    for k in range(0,len(matrix)):
        aux1=np.where((rlat>=matrix[k,0]-0.25)&(rlat<=matrix[k,0]+0.25)&(rlon>=matrix[k,1]-0.25)&(rlon<=matrix[k,1]+0.25))
        index_list.insert(k+1,aux1)
    # print(index_list)
    # print(len(index_list))
    # print(index_list[1])
    return index_list,matrix

def process_data_v6(files,indexes):
    # P = np.array(ds.Power) #FRP product
    #####################################################################
    #Transfom the satellite coodinates to lat-lon and selecting the box of interess
    # print(matrix[k,0])

    # caixa = (rlat>=matrix[0,0]-0.5)&(rlat<=matrix[0,0]+0.5)&(rlon>=matrix[0,1]-0.5)&(rlon<=matrix[0,1]+0.5)
    # C_caixa = np.invert(caixa).astype(int)
    all_array_T = []
    all_array_P = []
    os.chdir(outdir)
    for i in range(0,len(files)):
      with fs.open(files[i], 'rb') as f:
          
        ds = xr.open_dataset(BytesIO(f.read()), engine='h5netcdf')
        try:
            #####################################################################
            #Dates and times information of the Data
            #print(files[i].split('/')[5])
            #print(prodbase)
            prodbase = files[i].split('/')[5][:23]
            #print(prodbase)
            starttime=files[i].split(prodbase)[1].split('_')[0]
            #print(starttime)
            year,julian,hhmm=starttime[:4],starttime[4:7],starttime[7:11]
            # plottitle=year+','+julian+','+hhmm
            # fpart = starttime+','+plottitle
            print('Processing year: {}, day: {}, hour: {}'.format(year,julian,hhmm)) #Processing Message    
            # code = (int(julian)+(int(hhmm)/100)/24+(int(hhmm) % 100)/60/24)
            # code = int(year) + (int(julian)+(int(hhmm)/100)/24+(int(hhmm) % 100)/60/24)/1000
            # code2 = int(year) + (int(julian)+(int(hhmm)/100)/24+(int(hhmm) % 100)/60/24)/365
            #####################################################################
            #FRP Data
            P = np.array(ds.Power)
            T = np.array(ds.Temp)
            # A = np.array(ds.Area)
            
            # P_box_amazon = P[indexes[1]]
            # T_box_amazon = T[indexes[1]]
            P_box_amazon = P[indexes]
            T_box_amazon = T[indexes]
            array_P_box_amazon = P_box_amazon[~np.isnan(P_box_amazon)]
            array_T_box_amazon = T_box_amazon[~np.isnan(T_box_amazon)]
            
            # print(array_T_box_amazon)
            # print(array_T_box_amazon[:])'
            for value in array_T_box_amazon:
               
                outstring =  '%s\n' % value
                outfn.writelines(outstring)
            for value in array_P_box_amazon:
               
                outstring =  '%s\n' % value
                outfn2.writelines(outstring)
            # outfn.close()
            # all_array_T = np.append(all_array_T,array_T_box_amazon)
            # all_array_P = np.append(all_array_P,array_P_box_amazon)
            

        except OSError as error:
             print(error)
    #Close the file    
    # outstring = str(all_array_T)
    # outfn.writelines(outstring)
    outfn.close()
    outfn2.close()
    return all_array_T,all_array_P
###############################################################################
def plot_Temp(filename,array_temp):
    
    pyplot.clf()
    pyplot.title(filename)
    binwidth = 25
    pyplot.hist(array_temp,bins=np.arange(min(array_temp), 2000 + binwidth, binwidth))
    pyplot.savefig(filename+'.png',dpi=200)
    
    return 
    
def plot_FRP(filename,array_frp):
    
    pyplot.clf()
    pyplot.title(filename)
    binwidth = 50
    pyplot.hist(array_frp,bins=np.arange(min(array_frp), max(array_frp) + binwidth, binwidth))
    pyplot.savefig(filename+'.png',dpi=200)
    
    return 


###############################################################################
# Define input and output folders and file
datadir = 'C:/Users/thiag/OneDrive/Documentos/Projeto_Mestrado/Julho23/fire_dinamics/'
# datadir = '/home/thiagovg//Documentos/Projeto_Mestrado/Julho23/fire_dinamics_graphs/' # ubuntu old version
# datadir2 = '/home/thiagovg//Documentos/Projeto_Mestrado/Julho23'


# data = sorted(glob.glob(datadir2+'/FEER*.csv'))
# dados_feer = pd.read_csv(data[0])

outdir  = datadir+'output/'
# outfile = outdir+'goes_results_box_emission_rate_test_cerrado_cluster_v7.csv'
outfile = outdir+'array_T_data_v3.csv'
outfile2 = outdir+'array_P_data_test_v2.csv'
###############################################################################

#Define constants
###############################################################################
###############################################################################
# Define a ROI in degrees
#minlon,maxlon,minlat,maxlat=-80,-40,-30,5
#minlon,maxlon,minlat,maxlat=-61,-53,-20,-14
#minlon,maxlon,minlat,maxlat=-58,-56,-18,-16
minlon,maxlon,minlat,maxlat=-57,-54,-9,-6 #Amazon small box
# minlon,maxlon,minlat,maxlat=-72.5,-48.5,-9.5,-5.5 #Amazon big box
# minlon,maxlon,minlat,maxlat=-72,-48,-9,-6 #Amazon big box v2
# minlon,maxlon,minlat,maxlat=-57.5,-56.5,-17.5,-16.5 # cerrado big box
# minlon,maxlon,minlat,maxlat=-57.25,-57,-17.25,-17 # cerrado cluster 210
# @jit(nopython=True)
###############################################################################
###############################################################################
#Define the file header
aux1 ='array_temp\n'
aux2 ='array_frp\n'
header = aux1
header2 = aux2
# # print(header)
outstring=''
outfn = open(outfile, 'w')
outfn.writelines(header) 
outfn2 = open(outfile2, 'w')
outfn2.writelines(header2) 

###############################################################################
###############################################################################
# Initialize S3 file system
# fs = s3fs.S3FileSystem(anon=True)
fs = S3FileSystem(anon=True)

###############################################################################,
#Starting message
print
print('Compiling statistics')
print 

# start = time.time()
rlat,rlon = get_lat_lon(fs)
# end = time.time()
# print(end - start)
# start = time.time()
# Indexes = get_indexes(minlon,maxlon,minlat,maxlat,rlat,rlon,M)
Indexes,M = get_indexes_v2(minlon,maxlon,minlat,maxlat,rlat,rlon)
# end = time.time()
# print(end - start)
start_year,end_year,start_day,end_day,start_hour,end_our = 2020,2020,190,300,0,24
# lim_inf_smold,lim_sup_smold,lim_inf_flame,lim_sup_flame = 500,700,800,1200
# start = time.time()
data_list = get_files(start_year,end_year,start_day,end_day,start_hour,end_our)
# end = time.time()
# print(end - start)
# print(data_list[len(data_list)-1])
# print(len(data_list))

# start = time.time()
array_T,array_P = process_data_v6(data_list,Indexes[0])
# plot_Temp('array_temp_test4',array_T)
# plot_FRP('array_frp_test4',array_P)
# end = time.time()
# print(end - start)


